// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGW8gvJ2Xqo8C3_AHH5hrEA1wVsC39MQ',
    appId: '1:173690658006:web:78e911ee4c20f54fa4fd77',
    messagingSenderId: '173690658006',
    projectId: 'rideassist-ravelle',
    authDomain: 'rideassist-ravelle.firebaseapp.com',
    storageBucket: 'rideassist-ravelle.firebasestorage.app',
    measurementId: 'G-HVX06MRVR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fkO3uzB3VSQHB1Tz07m2darQCnVsQkw',
    appId: '1:173690658006:android:c82b6966daba0b9da4fd77',
    messagingSenderId: '173690658006',
    projectId: 'rideassist-ravelle',
    storageBucket: 'rideassist-ravelle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7R-st-PUzuRHclnJRBFI7hndp-9Uk10',
    appId: '1:173690658006:ios:7440e6a664e6ef10a4fd77',
    messagingSenderId: '173690658006',
    projectId: 'rideassist-ravelle',
    storageBucket: 'rideassist-ravelle.firebasestorage.app',
    iosBundleId: 'com.example.rideAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7R-st-PUzuRHclnJRBFI7hndp-9Uk10',
    appId: '1:173690658006:ios:7440e6a664e6ef10a4fd77',
    messagingSenderId: '173690658006',
    projectId: 'rideassist-ravelle',
    storageBucket: 'rideassist-ravelle.firebasestorage.app',
    iosBundleId: 'com.example.rideAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGW8gvJ2Xqo8C3_AHH5hrEA1wVsC39MQ',
    appId: '1:173690658006:web:ac6b625e8a21a155a4fd77',
    messagingSenderId: '173690658006',
    projectId: 'rideassist-ravelle',
    authDomain: 'rideassist-ravelle.firebaseapp.com',
    storageBucket: 'rideassist-ravelle.firebasestorage.app',
    measurementId: 'G-7TB6KLD4R0',
  );
}
